runtime: nodejs14
env: standard
instance_class: F1
manual_scaling:
  instances: 1
env_variables:
  DATABASE_URL: "mongodb+srv://penny-user:rWAEFWQnh6gWA5xH@mycluster.ex8oh.mongodb.net/myFirstDatabase?retryWrites=true"


